#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 29-10-2013 14:12
# Generated By: rmul
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$SaveButton = New-Object System.Windows.Forms.Button
$ExitButton = New-Object System.Windows.Forms.Button
$MaintabControl = New-Object System.Windows.Forms.TabControl
$ConfigtabPage = New-Object System.Windows.Forms.TabPage
$ConfigurationdataGridViewlabel = New-Object System.Windows.Forms.Label
$ConfigurationdataGridView1label = New-Object System.Windows.Forms.Label
$ConfigurationdataGridView2label = New-Object System.Windows.Forms.Label
$ConfigurationdataGridView2 = New-Object System.Windows.Forms.DataGridView
$ConfigurationdataGridView1 = New-Object System.Windows.Forms.DataGridView
$ConfigSavebutton = New-Object System.Windows.Forms.Button
$ConfigurationdataGridView = New-Object System.Windows.Forms.DataGridView
$ConfigLoadbutton = New-Object System.Windows.Forms.Button
$ConfigFileLabel = New-Object System.Windows.Forms.Label
$OUtabPage = New-Object System.Windows.Forms.TabPage
$OUbutton = New-Object System.Windows.Forms.Button
$OUtreeView1 = New-Object System.Windows.Forms.TreeView
$GPOtabPage = New-Object System.Windows.Forms.TabPage
$GPOlistBox = New-Object System.Windows.Forms.ListBox
$GPOlabel = New-Object System.Windows.Forms.Label
$tabControl1 = New-Object System.Windows.Forms.TabControl
$tabPage1 = New-Object System.Windows.Forms.TabPage
$SourceListBox = New-Object System.Windows.Forms.ListBox
$CompareButton = New-Object System.Windows.Forms.Button
$DestListBox = New-Object System.Windows.Forms.ListBox
$CompareGPOtabPage = New-Object System.Windows.Forms.TabPage
$CompareGPObutton = New-Object System.Windows.Forms.Button
$DomainlistBox = New-Object System.Windows.Forms.ListBox
$OtherGPOlistBox = New-Object System.Windows.Forms.ListBox
$tabPage2 = New-Object System.Windows.Forms.TabPage
$GPOBackupDiffbutton = New-Object System.Windows.Forms.Button
$GPOHistoryReportButton = New-Object System.Windows.Forms.Button
$GPOHistoryDataGridView = New-Object System.Windows.Forms.DataGridView
$GPOHistoryTextBox = New-Object System.Windows.Forms.TextBox
$GPOHistoryButton = New-Object System.Windows.Forms.Button
$WMIFiltertabPage = New-Object System.Windows.Forms.TabPage
$ReportTabPage = New-Object System.Windows.Forms.TabPage
$openFileDialog1 = New-Object System.Windows.Forms.OpenFileDialog
$saveFileDialog1 = New-Object System.Windows.Forms.SaveFileDialog
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$handler_OtherGPOlistBox_SelectedIndexChanged= 
{
#TODO: Place custom script here

}

$handler_DomainlistBox_SelectedIndexChanged= 
{
#TODO: Place custom script here

}

$handler_CompareGPObutton_Click= 
{
#TODO: Place custom script here

}

$handler_GPOHistoryButton_Click= 
{
#TODO: Place custom script here

}

$handler_GPOlistBox_SelectedIndexChanged= 
{
#TODO: Place custom script here

}

$handler_MaintabControl_SelectedIndexChanged= 
{
#TODO: Place custom script here

}

$handler_OUbutton_Click= 
{
#TODO: Place custom script here

}

$handler_GPOHistoryReportButton_Click= 
{
#TODO: Place custom script here

}

$handler_ConfigLoadbutton_Click= 
{
#TODO: Place custom script here

}

$handler_ConfigurationdataGridView_CellValueChanged= 
{
#TODO: Place custom script here

}

$handler_saveFileDialog1_FileOk= 
{
#TODO: Place custom script here

}

$handler_GPOBackupDiffbutton_Click= 
{
#TODO: Place custom script here

}

$handler_ConfigFile_OK= 
{
#TODO: Place custom script here

}

$handler_ConfigSavebutton_Click= 
{
#TODO: Place custom script here

}

$handler_ConfigFileLabel_Click= 
{
#TODO: Place custom script here

}

$handler_ExitButton_Click= 
{
#TODO: Place custom script here

}

$handler_CompareButton_Click= 
{
#TODO: Place custom script here

}

$SaveButton_OnClick= 
{
#TODO: Place custom script here

}

$handler_GPOHistoryDataGridView_SelectionChanged= 
{
#TODO: Place custom script here

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 702
$System_Drawing_Size.Width = 1140
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.Icon = [System.Drawing.Icon]::ExtractAssociatedIcon("$global:rootpath\Images\AD_TAP_Checker.ico")
$form1.Name = "form1"
$form1.Text = "AD Tap Checker"

$SaveButton.Anchor = 10

$SaveButton.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 977
$System_Drawing_Point.Y = 674
$SaveButton.Location = $System_Drawing_Point
$SaveButton.Name = "SaveButton"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$SaveButton.Size = $System_Drawing_Size
$SaveButton.TabIndex = 0
$SaveButton.Text = "Save as..."
$SaveButton.UseVisualStyleBackColor = $True
$SaveButton.Visible = $False
$SaveButton.add_Click($SaveButton_OnClick)

$form1.Controls.Add($SaveButton)

$ExitButton.Anchor = 10

$ExitButton.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 1058
$System_Drawing_Point.Y = 674
$ExitButton.Location = $System_Drawing_Point
$ExitButton.Name = "ExitButton"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$ExitButton.Size = $System_Drawing_Size
$ExitButton.TabIndex = 6
$ExitButton.Text = "Exit"
$ExitButton.UseVisualStyleBackColor = $True
$ExitButton.add_Click($handler_ExitButton_Click)

$form1.Controls.Add($ExitButton)

$MaintabControl.Anchor = 15
$MaintabControl.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 9
$System_Drawing_Point.Y = 12
$MaintabControl.Location = $System_Drawing_Point
$MaintabControl.Name = "MaintabControl"
$MaintabControl.SelectedIndex = 0
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 659
$System_Drawing_Size.Width = 1124
$MaintabControl.Size = $System_Drawing_Size
$MaintabControl.TabIndex = 14
$MaintabControl.add_SelectedIndexChanged($handler_MaintabControl_SelectedIndexChanged)

$form1.Controls.Add($MaintabControl)
$ConfigtabPage.AutoScroll = $True
$ConfigtabPage.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 22
$ConfigtabPage.Location = $System_Drawing_Point
$ConfigtabPage.Name = "ConfigtabPage"
$System_Windows_Forms_Padding = New-Object System.Windows.Forms.Padding
$System_Windows_Forms_Padding.All = 3
$System_Windows_Forms_Padding.Bottom = 3
$System_Windows_Forms_Padding.Left = 3
$System_Windows_Forms_Padding.Right = 3
$System_Windows_Forms_Padding.Top = 3
$ConfigtabPage.Padding = $System_Windows_Forms_Padding
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 633
$System_Drawing_Size.Width = 1116
$ConfigtabPage.Size = $System_Drawing_Size
$ConfigtabPage.TabIndex = 0
$ConfigtabPage.Text = "Configuration"
$ConfigtabPage.UseVisualStyleBackColor = $True

$MaintabControl.Controls.Add($ConfigtabPage)
$ConfigurationdataGridViewlabel.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 7
$System_Drawing_Point.Y = 84
$ConfigurationdataGridViewlabel.Location = $System_Drawing_Point
$ConfigurationdataGridViewlabel.Name = "ConfigurationdataGridViewlabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 206
$ConfigurationdataGridViewlabel.Size = $System_Drawing_Size
$ConfigurationdataGridViewlabel.TabIndex = 8
$ConfigurationdataGridViewlabel.Text = "Domain Configuration"

$ConfigtabPage.Controls.Add($ConfigurationdataGridViewlabel)

$ConfigurationdataGridView1label.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 7
$System_Drawing_Point.Y = 266
$ConfigurationdataGridView1label.Location = $System_Drawing_Point
$ConfigurationdataGridView1label.Name = "ConfigurationdataGridView1label"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 206
$ConfigurationdataGridView1label.Size = $System_Drawing_Size
$ConfigurationdataGridView1label.TabIndex = 7
$ConfigurationdataGridView1label.Text = "Report Save Location configuration"

$ConfigtabPage.Controls.Add($ConfigurationdataGridView1label)

$ConfigurationdataGridView2label.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 7
$System_Drawing_Point.Y = 448
$ConfigurationdataGridView2label.Location = $System_Drawing_Point
$ConfigurationdataGridView2label.Name = "ConfigurationdataGridView2label"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 206
$ConfigurationdataGridView2label.Size = $System_Drawing_Size
$ConfigurationdataGridView2label.TabIndex = 6
$ConfigurationdataGridView2label.Text = "eMail Configuration"

$ConfigtabPage.Controls.Add($ConfigurationdataGridView2label)

$ConfigurationdataGridView2.Anchor = 13
$ConfigurationdataGridView2.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 477
$ConfigurationdataGridView2.Location = $System_Drawing_Point
$ConfigurationdataGridView2.Name = "ConfigurationdataGridView2"
$ConfigurationdataGridView2.RowHeadersVisible = $False
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 150
$System_Drawing_Size.Width = 1104
$ConfigurationdataGridView2.Size = $System_Drawing_Size
$ConfigurationdataGridView2.TabIndex = 5

$ConfigtabPage.Controls.Add($ConfigurationdataGridView2)

$ConfigurationdataGridView1.Anchor = 13
$ConfigurationdataGridView1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 295
$ConfigurationdataGridView1.Location = $System_Drawing_Point
$ConfigurationdataGridView1.Name = "ConfigurationdataGridView1"
$ConfigurationdataGridView1.RowHeadersVisible = $False
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 150
$System_Drawing_Size.Width = 1103
$ConfigurationdataGridView1.Size = $System_Drawing_Size
$ConfigurationdataGridView1.TabIndex = 4

$ConfigtabPage.Controls.Add($ConfigurationdataGridView1)

$ConfigSavebutton.Anchor = 9

$ConfigSavebutton.DataBindings.DefaultDataSourceUpdateMode = 0
$ConfigSavebutton.Enabled = $False

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 990
$System_Drawing_Point.Y = 7
$ConfigSavebutton.Location = $System_Drawing_Point
$ConfigSavebutton.Name = "ConfigSavebutton"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 120
$ConfigSavebutton.Size = $System_Drawing_Size
$ConfigSavebutton.TabIndex = 3
$ConfigSavebutton.Text = "Save"
$ConfigSavebutton.UseVisualStyleBackColor = $True
$ConfigSavebutton.add_Click($handler_ConfigSavebutton_Click)

$ConfigtabPage.Controls.Add($ConfigSavebutton)

$ConfigurationdataGridView.Anchor = 13
$ConfigurationdataGridView.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 113
$ConfigurationdataGridView.Location = $System_Drawing_Point
$ConfigurationdataGridView.Name = "ConfigurationdataGridView"
$ConfigurationdataGridView.RowHeadersVisible = $False
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 150
$System_Drawing_Size.Width = 1103
$ConfigurationdataGridView.Size = $System_Drawing_Size
$ConfigurationdataGridView.TabIndex = 2
$ConfigurationdataGridView.add_CellValueChanged($handler_ConfigurationdataGridView_CellValueChanged)

$ConfigtabPage.Controls.Add($ConfigurationdataGridView)

$ConfigLoadbutton.Anchor = 9

$ConfigLoadbutton.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 863
$System_Drawing_Point.Y = 6
$ConfigLoadbutton.Location = $System_Drawing_Point
$ConfigLoadbutton.Name = "ConfigLoadbutton"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 120
$ConfigLoadbutton.Size = $System_Drawing_Size
$ConfigLoadbutton.TabIndex = 0
$ConfigLoadbutton.Text = "Open"
$ConfigLoadbutton.UseVisualStyleBackColor = $True
$ConfigLoadbutton.add_Click($handler_ConfigLoadbutton_Click)

$ConfigtabPage.Controls.Add($ConfigLoadbutton)

$ConfigFileLabel.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 11
$ConfigFileLabel.Location = $System_Drawing_Point
$ConfigFileLabel.Name = "ConfigFileLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 800
$ConfigFileLabel.Size = $System_Drawing_Size
$ConfigFileLabel.TabIndex = 1
$ConfigFileLabel.Text = "Current Configuration:"
$ConfigFileLabel.add_Click($handler_ConfigFileLabel_Click)

$ConfigtabPage.Controls.Add($ConfigFileLabel)


$OUtabPage.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 22
$OUtabPage.Location = $System_Drawing_Point
$OUtabPage.Name = "OUtabPage"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 633
$System_Drawing_Size.Width = 1116
$OUtabPage.Size = $System_Drawing_Size
$OUtabPage.TabIndex = 4
$OUtabPage.Text = "OUs"
$OUtabPage.UseVisualStyleBackColor = $True

$MaintabControl.Controls.Add($OUtabPage)

$OUbutton.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 416
$System_Drawing_Point.Y = 12
$OUbutton.Location = $System_Drawing_Point
$OUbutton.Name = "OUbutton"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$OUbutton.Size = $System_Drawing_Size
$OUbutton.TabIndex = 1
$OUbutton.Text = "Refresh"
$OUbutton.UseVisualStyleBackColor = $True
$OUbutton.add_Click($handler_OUbutton_Click)

$OUtabPage.Controls.Add($OUbutton)

$OUtreeView1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 3
$System_Drawing_Point.Y = 12
$OUtreeView1.Location = $System_Drawing_Point
$OUtreeView1.Name = "OUtreeView1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 514
$System_Drawing_Size.Width = 407
$OUtreeView1.Size = $System_Drawing_Size
$OUtreeView1.TabIndex = 0

$OUtabPage.Controls.Add($OUtreeView1)


$GPOtabPage.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 22
$GPOtabPage.Location = $System_Drawing_Point
$GPOtabPage.Name = "GPOtabPage"
$System_Windows_Forms_Padding = New-Object System.Windows.Forms.Padding
$System_Windows_Forms_Padding.All = 3
$System_Windows_Forms_Padding.Bottom = 3
$System_Windows_Forms_Padding.Left = 3
$System_Windows_Forms_Padding.Right = 3
$System_Windows_Forms_Padding.Top = 3
$GPOtabPage.Padding = $System_Windows_Forms_Padding
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 633
$System_Drawing_Size.Width = 1116
$GPOtabPage.Size = $System_Drawing_Size
$GPOtabPage.TabIndex = 1
$GPOtabPage.Text = "GPOs"
$GPOtabPage.UseVisualStyleBackColor = $True

$MaintabControl.Controls.Add($GPOtabPage)
$GPOlistBox.Anchor = 7
$GPOlistBox.DataBindings.DefaultDataSourceUpdateMode = 0
$GPOlistBox.FormattingEnabled = $True
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 24
$GPOlistBox.Location = $System_Drawing_Point
$GPOlistBox.Name = "GPOlistBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 602
$System_Drawing_Size.Width = 288
$GPOlistBox.Size = $System_Drawing_Size
$GPOlistBox.TabIndex = 2
$GPOlistBox.Visible = $False
$GPOlistBox.add_SelectedIndexChanged($handler_GPOlistBox_SelectedIndexChanged)

$GPOtabPage.Controls.Add($GPOlistBox)

$GPOlabel.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 3
$System_Drawing_Point.Y = 10
$GPOlabel.Location = $System_Drawing_Point
$GPOlabel.Name = "GPOlabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 19
$System_Drawing_Size.Width = 119
$GPOlabel.Size = $System_Drawing_Size
$GPOlabel.TabIndex = 13
$GPOlabel.Text = "Group Policy Objects"

$GPOtabPage.Controls.Add($GPOlabel)

$tabControl1.Anchor = 15
$tabControl1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 300
$System_Drawing_Point.Y = 3
$tabControl1.Location = $System_Drawing_Point
$tabControl1.Name = "tabControl1"
$tabControl1.SelectedIndex = 0
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 624
$System_Drawing_Size.Width = 810
$tabControl1.Size = $System_Drawing_Size
$tabControl1.TabIndex = 10
$tabControl1.Visible = $False

$GPOtabPage.Controls.Add($tabControl1)
$tabPage1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 22
$tabPage1.Location = $System_Drawing_Point
$tabPage1.Name = "tabPage1"
$System_Windows_Forms_Padding = New-Object System.Windows.Forms.Padding
$System_Windows_Forms_Padding.All = 3
$System_Windows_Forms_Padding.Bottom = 3
$System_Windows_Forms_Padding.Left = 3
$System_Windows_Forms_Padding.Right = 3
$System_Windows_Forms_Padding.Top = 3
$tabPage1.Padding = $System_Windows_Forms_Padding
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 598
$System_Drawing_Size.Width = 802
$tabPage1.Size = $System_Drawing_Size
$tabPage1.TabIndex = 0
$tabPage1.Text = "Compare between Domains"
$tabPage1.UseVisualStyleBackColor = $True

$tabControl1.Controls.Add($tabPage1)
$SourceListBox.DataBindings.DefaultDataSourceUpdateMode = 0
$SourceListBox.FormattingEnabled = $True
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 6
$SourceListBox.Location = $System_Drawing_Point
$SourceListBox.Name = "SourceListBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 95
$System_Drawing_Size.Width = 91
$SourceListBox.Size = $System_Drawing_Size
$SourceListBox.TabIndex = 7

$tabPage1.Controls.Add($SourceListBox)


$CompareButton.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 103
$System_Drawing_Point.Y = 6
$CompareButton.Location = $System_Drawing_Point
$CompareButton.Name = "CompareButton"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 94
$System_Drawing_Size.Width = 37
$CompareButton.Size = $System_Drawing_Size
$CompareButton.TabIndex = 9
$CompareButton.Text = "Compare"
$CompareButton.UseVisualStyleBackColor = $True
$CompareButton.add_Click($handler_CompareButton_Click)

$tabPage1.Controls.Add($CompareButton)

$DestListBox.DataBindings.DefaultDataSourceUpdateMode = 0
$DestListBox.FormattingEnabled = $True
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 146
$System_Drawing_Point.Y = 6
$DestListBox.Location = $System_Drawing_Point
$DestListBox.Name = "DestListBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 95
$System_Drawing_Size.Width = 91
$DestListBox.Size = $System_Drawing_Size
$DestListBox.TabIndex = 8

$tabPage1.Controls.Add($DestListBox)


$CompareGPOtabPage.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 22
$CompareGPOtabPage.Location = $System_Drawing_Point
$CompareGPOtabPage.Name = "CompareGPOtabPage"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 598
$System_Drawing_Size.Width = 802
$CompareGPOtabPage.Size = $System_Drawing_Size
$CompareGPOtabPage.TabIndex = 2
$CompareGPOtabPage.Text = "Compare GPO"
$CompareGPOtabPage.UseVisualStyleBackColor = $True

$tabControl1.Controls.Add($CompareGPOtabPage)

$CompareGPObutton.DataBindings.DefaultDataSourceUpdateMode = 0
$CompareGPObutton.Enabled = $False

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 276
$System_Drawing_Point.Y = 106
$CompareGPObutton.Location = $System_Drawing_Point
$CompareGPObutton.Name = "CompareGPObutton"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$CompareGPObutton.Size = $System_Drawing_Size
$CompareGPObutton.TabIndex = 2
$CompareGPObutton.Text = "Compare"
$CompareGPObutton.UseVisualStyleBackColor = $True
$CompareGPObutton.add_Click($handler_CompareGPObutton_Click)

$CompareGPOtabPage.Controls.Add($CompareGPObutton)

$DomainlistBox.DataBindings.DefaultDataSourceUpdateMode = 0
$DomainlistBox.FormattingEnabled = $True
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 276
$System_Drawing_Point.Y = 4
$DomainlistBox.Location = $System_Drawing_Point
$DomainlistBox.Name = "DomainlistBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 95
$System_Drawing_Size.Width = 120
$DomainlistBox.Size = $System_Drawing_Size
$DomainlistBox.TabIndex = 1
$DomainlistBox.add_SelectedIndexChanged($handler_DomainlistBox_SelectedIndexChanged)

$CompareGPOtabPage.Controls.Add($DomainlistBox)

$OtherGPOlistBox.DataBindings.DefaultDataSourceUpdateMode = 0
$OtherGPOlistBox.FormattingEnabled = $True
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 3
$System_Drawing_Point.Y = 3
$OtherGPOlistBox.Location = $System_Drawing_Point
$OtherGPOlistBox.Name = "OtherGPOlistBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 589
$System_Drawing_Size.Width = 266
$OtherGPOlistBox.Size = $System_Drawing_Size
$OtherGPOlistBox.TabIndex = 0
$OtherGPOlistBox.add_SelectedIndexChanged($handler_OtherGPOlistBox_SelectedIndexChanged)

$CompareGPOtabPage.Controls.Add($OtherGPOlistBox)


$tabPage2.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 22
$tabPage2.Location = $System_Drawing_Point
$tabPage2.Name = "tabPage2"
$System_Windows_Forms_Padding = New-Object System.Windows.Forms.Padding
$System_Windows_Forms_Padding.All = 3
$System_Windows_Forms_Padding.Bottom = 3
$System_Windows_Forms_Padding.Left = 3
$System_Windows_Forms_Padding.Right = 3
$System_Windows_Forms_Padding.Top = 3
$tabPage2.Padding = $System_Windows_Forms_Padding
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 598
$System_Drawing_Size.Width = 802
$tabPage2.Size = $System_Drawing_Size
$tabPage2.TabIndex = 1
$tabPage2.Text = "GPO History"
$tabPage2.UseVisualStyleBackColor = $True

$tabControl1.Controls.Add($tabPage2)
$GPOBackupDiffbutton.Anchor = 9

$GPOBackupDiffbutton.DataBindings.DefaultDataSourceUpdateMode = 0
$GPOBackupDiffbutton.Enabled = $False

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 660
$System_Drawing_Point.Y = 270
$GPOBackupDiffbutton.Location = $System_Drawing_Point
$GPOBackupDiffbutton.Name = "GPOBackupDiffbutton"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 136
$GPOBackupDiffbutton.Size = $System_Drawing_Size
$GPOBackupDiffbutton.TabIndex = 4
$GPOBackupDiffbutton.Text = "Diff with previous"
$GPOBackupDiffbutton.UseVisualStyleBackColor = $True
$GPOBackupDiffbutton.add_Click($handler_GPOBackupDiffbutton_Click)

$tabPage2.Controls.Add($GPOBackupDiffbutton)

$GPOHistoryReportButton.Anchor = 9

$GPOHistoryReportButton.DataBindings.DefaultDataSourceUpdateMode = 0
$GPOHistoryReportButton.Enabled = $False

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 660
$System_Drawing_Point.Y = 241
$GPOHistoryReportButton.Location = $System_Drawing_Point
$GPOHistoryReportButton.Name = "GPOHistoryReportButton"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 136
$GPOHistoryReportButton.Size = $System_Drawing_Size
$GPOHistoryReportButton.TabIndex = 3
$GPOHistoryReportButton.Text = "GPOBackup Report"
$GPOHistoryReportButton.UseVisualStyleBackColor = $True
$GPOHistoryReportButton.add_Click($handler_GPOHistoryReportButton_Click)

$tabPage2.Controls.Add($GPOHistoryReportButton)

$GPOHistoryDataGridView.Anchor = 15
$GPOHistoryDataGridView.AutoSizeColumnsMode = 6
$System_Windows_Forms_DataGridViewCellStyle_46 = New-Object System.Windows.Forms.DataGridViewCellStyle
$System_Windows_Forms_DataGridViewCellStyle_46.Alignment = 16
$System_Windows_Forms_DataGridViewCellStyle_46.BackColor = [System.Drawing.Color]::FromArgb(255,240,240,240)
$System_Windows_Forms_DataGridViewCellStyle_46.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,0,3,1)
$System_Windows_Forms_DataGridViewCellStyle_46.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
$System_Windows_Forms_DataGridViewCellStyle_46.SelectionBackColor = [System.Drawing.Color]::FromArgb(255,51,153,255)
$System_Windows_Forms_DataGridViewCellStyle_46.SelectionForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_46.WrapMode = 1
$GPOHistoryDataGridView.ColumnHeadersDefaultCellStyle = $System_Windows_Forms_DataGridViewCellStyle_46
$System_Windows_Forms_DataGridViewTextBoxColumn_47 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_47.HeaderText = "Domain"
$System_Windows_Forms_DataGridViewTextBoxColumn_47.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_47.Width = 68

$GPOHistoryDataGridView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_47)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_48 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_48.HeaderText = "Last Modified"
$System_Windows_Forms_DataGridViewTextBoxColumn_48.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_48.Width = 95

$GPOHistoryDataGridView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_48)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_49 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_49.HeaderText = "Backed Up"
$System_Windows_Forms_DataGridViewTextBoxColumn_49.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_49.Width = 86

$GPOHistoryDataGridView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_49)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_50 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_50.HeaderText = "BackupID"
$System_Windows_Forms_DataGridViewTextBoxColumn_50.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_50.Width = 80

$GPOHistoryDataGridView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_50)|Out-Null
$GPOHistoryDataGridView.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Windows_Forms_DataGridViewCellStyle_51 = New-Object System.Windows.Forms.DataGridViewCellStyle
$System_Windows_Forms_DataGridViewCellStyle_51.Alignment = 16
$System_Windows_Forms_DataGridViewCellStyle_51.BackColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_51.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,0,3,1)
$System_Windows_Forms_DataGridViewCellStyle_51.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
$System_Windows_Forms_DataGridViewCellStyle_51.SelectionBackColor = [System.Drawing.Color]::FromArgb(255,51,153,255)
$System_Windows_Forms_DataGridViewCellStyle_51.SelectionForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_51.WrapMode = 2
$GPOHistoryDataGridView.DefaultCellStyle = $System_Windows_Forms_DataGridViewCellStyle_51
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 7
$System_Drawing_Point.Y = 241
$GPOHistoryDataGridView.Location = $System_Drawing_Point
$GPOHistoryDataGridView.Name = "GPOHistoryDataGridView"
$GPOHistoryDataGridView.SelectionMode = 1
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 351
$System_Drawing_Size.Width = 643
$GPOHistoryDataGridView.Size = $System_Drawing_Size
$GPOHistoryDataGridView.TabIndex = 2
$GPOHistoryDataGridView.add_SelectionChanged($handler_GPOHistoryDataGridView_SelectionChanged)

$tabPage2.Controls.Add($GPOHistoryDataGridView)

$GPOHistoryTextBox.Anchor = 13
$GPOHistoryTextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 7
$System_Drawing_Point.Y = 37
$GPOHistoryTextBox.Location = $System_Drawing_Point
$GPOHistoryTextBox.Multiline = $True
$GPOHistoryTextBox.Name = "GPOHistoryTextBox"
$GPOHistoryTextBox.ReadOnly = $True
$GPOHistoryTextBox.ScrollBars = 3
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 197
$System_Drawing_Size.Width = 789
$GPOHistoryTextBox.Size = $System_Drawing_Size
$GPOHistoryTextBox.TabIndex = 1

$tabPage2.Controls.Add($GPOHistoryTextBox)


$GPOHistoryButton.DataBindings.DefaultDataSourceUpdateMode = 0
$GPOHistoryButton.Enabled = $False

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 7
$System_Drawing_Point.Y = 7
$GPOHistoryButton.Location = $System_Drawing_Point
$GPOHistoryButton.Name = "GPOHistoryButton"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$GPOHistoryButton.Size = $System_Drawing_Size
$GPOHistoryButton.TabIndex = 0
$GPOHistoryButton.Text = "Get History"
$GPOHistoryButton.UseVisualStyleBackColor = $True
$GPOHistoryButton.add_Click($handler_GPOHistoryButton_Click)

$tabPage2.Controls.Add($GPOHistoryButton)




$WMIFiltertabPage.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 22
$WMIFiltertabPage.Location = $System_Drawing_Point
$WMIFiltertabPage.Name = "WMIFiltertabPage"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 633
$System_Drawing_Size.Width = 1116
$WMIFiltertabPage.Size = $System_Drawing_Size
$WMIFiltertabPage.TabIndex = 2
$WMIFiltertabPage.Text = "WMI Filters"
$WMIFiltertabPage.UseVisualStyleBackColor = $True

$MaintabControl.Controls.Add($WMIFiltertabPage)

$ReportTabPage.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 22
$ReportTabPage.Location = $System_Drawing_Point
$ReportTabPage.Name = "ReportTabPage"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 633
$System_Drawing_Size.Width = 1116
$ReportTabPage.Size = $System_Drawing_Size
$ReportTabPage.TabIndex = 3
$ReportTabPage.Text = "ReportViewer"
$ReportTabPage.UseVisualStyleBackColor = $True

$MaintabControl.Controls.Add($ReportTabPage)


$openFileDialog1.DefaultExt = "xml"
$openFileDialog1.FileName = "AD_TAP_Checker.xml"
$openFileDialog1.Filter = "Config files (*.xml)|*.xml|All files (*.*)|*.*"
$openFileDialog1.InitialDirectory = "."
$openFileDialog1.ShowHelp = $True
$openFileDialog1.add_FileOk($handler_ConfigFile_OK)

$saveFileDialog1.CreatePrompt = $True
$saveFileDialog1.DefaultExt = "html"
$saveFileDialog1.Filter = "HTML report (*.html)|*.html|All files (*.*)|*.*"
$saveFileDialog1.ShowHelp = $True
$saveFileDialog1.add_FileOk($handler_saveFileDialog1_FileOk)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
